//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.261
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZsTemplate.Languages.ZsForm {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class String {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal String() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZsTemplate.Languages.ZsForm.String", typeof(String).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Generate CD Key.
        /// </summary>
        internal static string Button_Generate {
            get {
                return ResourceManager.GetString("Button_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Write the code in the memory of the game.
        /// </summary>
        internal static string Button_Inject {
            get {
                return ResourceManager.GetString("Button_Inject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Refresh.
        /// </summary>
        internal static string Button_Refresh {
            get {
                return ResourceManager.GetString("Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Apply.
        /// </summary>
        internal static string Button_RegeditApply {
            get {
                return ResourceManager.GetString("Button_RegeditApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Explore.
        /// </summary>
        internal static string Button_RegeditExplore {
            get {
                return ResourceManager.GetString("Button_RegeditExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rebuilt System Registry key.
        /// </summary>
        internal static string Button_RegeditRebuilt {
            get {
                return ResourceManager.GetString("Button_RegeditRebuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Write the code in the System Registry.
        /// </summary>
        internal static string Button_Use {
            get {
                return ResourceManager.GetString("Button_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Saved CD Key list.
        /// </summary>
        internal static string Column_CdKey {
            get {
                return ResourceManager.GetString("Column_CdKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Exit.
        /// </summary>
        internal static string File_Exit {
            get {
                return ResourceManager.GetString("File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Open....
        /// </summary>
        internal static string File_Open {
            get {
                return ResourceManager.GetString("File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save.
        /// </summary>
        internal static string File_Save {
            get {
                return ResourceManager.GetString("File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  System Registry key currently in use .
        /// </summary>
        internal static string GroupBox_CurrentRegistryPath {
            get {
                return ResourceManager.GetString("GroupBox_CurrentRegistryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New CD Key.
        /// </summary>
        internal static string Label_NewKey {
            get {
                return ResourceManager.GetString("Label_NewKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reg. CD Key.
        /// </summary>
        internal static string Label_RegKey {
            get {
                return ResourceManager.GetString("Label_RegKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Copy.
        /// </summary>
        internal static string Menu_Copy {
            get {
                return ResourceManager.GetString("Menu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete.
        /// </summary>
        internal static string Menu_Delete {
            get {
                return ResourceManager.GetString("Menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Quick Validate.
        /// </summary>
        internal static string Menu_FastValidate {
            get {
                return ResourceManager.GetString("Menu_FastValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fix.
        /// </summary>
        internal static string Menu_Fix {
            get {
                return ResourceManager.GetString("Menu_Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Get PBGuid.
        /// </summary>
        internal static string Menu_GetGuid {
            get {
                return ResourceManager.GetString("Menu_GetGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Paste.
        /// </summary>
        internal static string Menu_Paste {
            get {
                return ResourceManager.GetString("Menu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove.
        /// </summary>
        internal static string Menu_Remove {
            get {
                return ResourceManager.GetString("Menu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save.
        /// </summary>
        internal static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Validate whit server.
        /// </summary>
        internal static string Menu_ServerValidate {
            get {
                return ResourceManager.GetString("Menu_ServerValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Use.
        /// </summary>
        internal static string Menu_Use {
            get {
                return ResourceManager.GetString("Menu_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Validate.
        /// </summary>
        internal static string Menu_Validate {
            get {
                return ResourceManager.GetString("Menu_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ?.
        /// </summary>
        internal static string Qt {
            get {
                return ResourceManager.GetString("Qt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a About.
        /// </summary>
        internal static string Qt_About {
            get {
                return ResourceManager.GetString("Qt_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Help.
        /// </summary>
        internal static string Qt_Help {
            get {
                return ResourceManager.GetString("Qt_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Update.
        /// </summary>
        internal static string Qt_Update {
            get {
                return ResourceManager.GetString("Qt_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This CD Key not exist.
        /// </summary>
        internal static string RemoveKey_NotFound {
            get {
                return ResourceManager.GetString("RemoveKey_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to delete this CD Key ?.
        /// </summary>
        internal static string RemoveKey_Question {
            get {
                return ResourceManager.GetString("RemoveKey_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This CD Key is already stored.
        /// </summary>
        internal static string SaveKey_DuplicateFound {
            get {
                return ResourceManager.GetString("SaveKey_DuplicateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to save this CD Key ?.
        /// </summary>
        internal static string SaveKey_Question {
            get {
                return ResourceManager.GetString("SaveKey_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CD Key.
        /// </summary>
        internal static string TabPage_1 {
            get {
                return ResourceManager.GetString("TabPage_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reg. Editor.
        /// </summary>
        internal static string TabPage_2 {
            get {
                return ResourceManager.GetString("TabPage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a by Zs&apos; Logic.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hide CD Key list.
        /// </summary>
        internal static string ToggleKeyList_Hide {
            get {
                return ResourceManager.GetString("ToggleKeyList_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Show CD Key list.
        /// </summary>
        internal static string ToggleKeyList_Show {
            get {
                return ResourceManager.GetString("ToggleKeyList_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tools.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Language.
        /// </summary>
        internal static string Tools_Language {
            get {
                return ResourceManager.GetString("Tools_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settings....
        /// </summary>
        internal static string Tools_Settings {
            get {
                return ResourceManager.GetString("Tools_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a English ( en-EN ).
        /// </summary>
        internal static string Unlocalize_Menu_EN {
            get {
                return ResourceManager.GetString("Unlocalize_Menu_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Italiano ( it-IT ).
        /// </summary>
        internal static string Unlocalize_Menu_IT {
            get {
                return ResourceManager.GetString("Unlocalize_Menu_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a -.
        /// </summary>
        internal static string Unlocalize_Menu_Spacer {
            get {
                return ResourceManager.GetString("Unlocalize_Menu_Spacer", resourceCulture);
            }
        }
    }
}
