//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.261
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZsTemplate.Languages.Error {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class String {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal String() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZsTemplate.Languages.Error.String", typeof(String).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The CD Guid is invalid, an error is occurred during the generation
        ///The DLL could be corrupt.
        /// </summary>
        internal static string CDGuid {
            get {
                return ResourceManager.GetString("CDGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CD Guid is invalid.
        /// </summary>
        internal static string CDGuidTip {
            get {
                return ResourceManager.GetString("CDGuidTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The CD Key code must be valid to perform this operation.
        /// </summary>
        internal static string CDKey {
            get {
                return ResourceManager.GetString("CDKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CD Key code is invalid.
        /// </summary>
        internal static string CDKeyTip {
            get {
                return ResourceManager.GetString("CDKeyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Has not been possible to locate the. dll.
        /// </summary>
        internal static string DllNotFound {
            get {
                return ResourceManager.GetString("DllNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dll is missing.
        /// </summary>
        internal static string DllNotFoundTip {
            get {
                return ResourceManager.GetString("DllNotFoundTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The game must be opened to perform this operation.
        /// </summary>
        internal static string GameHandle {
            get {
                return ResourceManager.GetString("GameHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Game is close.
        /// </summary>
        internal static string GameHandleTip {
            get {
                return ResourceManager.GetString("GameHandleTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A generic error was encountered.
        /// </summary>
        internal static string Generic {
            get {
                return ResourceManager.GetString("Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error.
        /// </summary>
        internal static string GenericTip {
            get {
                return ResourceManager.GetString("GenericTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error writing to the memory of the game.
        /// </summary>
        internal static string Injection {
            get {
                return ResourceManager.GetString("Injection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot write to memory.
        /// </summary>
        internal static string InjectionTip {
            get {
                return ResourceManager.GetString("InjectionTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The System Registry key does not contain the subkey &apos;codkey&apos;.
        /// </summary>
        internal static string Registry {
            get {
                return ResourceManager.GetString("Registry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The System Registry key cannot be empty.
        /// </summary>
        internal static string RegistryEmpty {
            get {
                return ResourceManager.GetString("RegistryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a System Registry key is empty.
        /// </summary>
        internal static string RegistryEmptyTip {
            get {
                return ResourceManager.GetString("RegistryEmptyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The System Registry key has been marked for deletion.
        /// </summary>
        internal static string RegistryIO {
            get {
                return ResourceManager.GetString("RegistryIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a System Registry key has been marked for deletion.
        /// </summary>
        internal static string RegistryIOTip {
            get {
                return ResourceManager.GetString("RegistryIOTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The System Registry key does does not terminate with &apos;Activision\Call of Duty 4&apos;.
        /// </summary>
        internal static string RegistryPeak {
            get {
                return ResourceManager.GetString("RegistryPeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a System Registry key must terminate with &apos;Activision\Call of Duty 4&apos;.
        /// </summary>
        internal static string RegistryPeakTip {
            get {
                return ResourceManager.GetString("RegistryPeakTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The System Registry key does not begin with a valid registry root.
        /// </summary>
        internal static string RegistryRoot {
            get {
                return ResourceManager.GetString("RegistryRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a System Registry key must begin with a valid registry root.
        /// </summary>
        internal static string RegistryRootTip {
            get {
                return ResourceManager.GetString("RegistryRootTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The user does not have the permissions required to read from the System Registry key.
        /// </summary>
        internal static string RegistrySecurityGet {
            get {
                return ResourceManager.GetString("RegistrySecurityGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insufficient permissions to read the System Registry key.
        /// </summary>
        internal static string RegistrySecurityGetTip {
            get {
                return ResourceManager.GetString("RegistrySecurityGetTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The user does not have the permissions required to modify the System Registry key.
        /// </summary>
        internal static string RegistrySecuritySet {
            get {
                return ResourceManager.GetString("RegistrySecuritySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insufficient permissions to write the System Registry key.
        /// </summary>
        internal static string RegistrySecuritySetTip {
            get {
                return ResourceManager.GetString("RegistrySecuritySetTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a System Registry key is invalid.
        /// </summary>
        internal static string RegistryTip {
            get {
                return ResourceManager.GetString("RegistryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The System Registry key is read-only, and thus cannot be written to.
        /// </summary>
        internal static string RegistryUnauthorizedAccess {
            get {
                return ResourceManager.GetString("RegistryUnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a System Registry key is read-only.
        /// </summary>
        internal static string RegistryUnauthorizedAccessTip {
            get {
                return ResourceManager.GetString("RegistryUnauthorizedAccessTip", resourceCulture);
            }
        }
    }
}
